---
- name: Distribution specific tasks
  ansible.builtin.include_tasks: ../../common_tasks/distribution_specific.yml
  vars:
    supported_distributions: [Fedora]

- name: Install
  block:
  - name: Show packages to install
    debug:
      var: common_packages_install

  - name: Install common packages
    package:
      name: "{{ common_packages_install }}"
      state: present
    become: true

- name: Remove
  when: common_packages_remove | length > 0
  block:
  - name: Show packages to remove
    debug:
      var: common_packages_remove
  - name: Remove unnecessary packages
    package:
      name: "{{ common_packages_remove }}"
      state: present
    become: true
