---
- name: Distribution specific tasks
  ansible.builtin.include_tasks: ../../common_tasks/distribution_specific.yml
  vars:
    supported_distributions: [Fedora]

- name: Install
  block:
    - name: Show packages to install
      ansible.builtin.debug:
        var: common_packages_install

    - name: Install common packages
      ansible.builtin.package:
        name: "{{ common_packages_install }}"
        state: present
      become: true

- name: Remove
  when: common_packages_remove | length > 0
  block:
    - name: Show packages to remove
      ansible.builtin.debug:
        var: common_packages_remove
    - name: Remove unnecessary packages
      ansible.builtin.package:
        name: "{{ common_packages_remove }}"
        state: present
      become: true
