---
- name: Install component
  ansible.builtin.package:
    name: "{{ component_packages }}"
    state: present
  become: true

- name: Add configuration files
  when: component_configuration_directory is defined
  block:
    - name: Ensure configuration directory exists
      ansible.builtin.file:
        path: "{{ component_configuration_directory }}"
        state: directory
        mode: u=rwx,g=rx,o=rx
    - name: Copy config file(s)
      ansible.builtin.template:
        src: "files/{{ item }}"
        dest: "{{ component_configuration_directory }}/{{ item }}"
        mode: u=rw,g=r,o=r
      loop: "{{ component_configuration_files }}"
  become: "{{ component_configuration_become | default(false) }}"
