---
- name: Ensure supported distribution
  ansible.builtin.assert:
    that:
      - ansible_distribution in supported_distributions
    fail_msg: "'{{ ansible_distribution }}' not supported. Supported distributions: {{ supported_distributions }}"
    quiet: true

- name: Include distribution specific vars
  ansible.builtin.include_vars: "{{ role_path }}/vars/{{ ansible_distribution }}.yml"

- name: Include distribution specific tasks
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/setup_{{ ansible_distribution }}.yml"
