---
- name: Rebuild font cache
  ansible.builtin.command: fc-cache -fv
  register: fc_cache
  changed_when: "'caching' in fc_cache.stdout or 'updated' in fc_cache.stdout or 'skipped' not in fc_cache.stdout"
