---
- name: Install Greetd
  ansible.builtin.include_tasks: ../../common_tasks/component_install.yml
  vars:
    component_packages: [greetd, tuigreet]
    component_configuration_directory: /etc/greetd/
    component_configuration_files: [config.toml]
    component_configuration_become: true

- name: Enable greetd service
  ansible.builtin.systemd:
    name: greetd
    enabled: true
  become: true
