---
- name: Install Greetd
  ansible.builtin.include_tasks: ../../common_tasks/component_install.yml
  vars:
    component_packages: [rofi-wayland]
    component_configuration_directory: ~/.config/rofi/
    component_configuration_files: [config.rasi, theme.rasi]
