---
hyprland_monitors_manual_enabled: false
hyprland_monitors_manual:
  - HDMI-A-2, 1920x1080, 0x0, 1
  - eDP-1, preferred, 0x-1080, 1
  - HDMI-A-1, disable

hyprland_terminal: kitty
hyprland_bar: waybar
hyprland_notification_daemon: mako
hyprland_file_manager: nautilus
hyprland_menu: rofi -show drun -show-icons

hyprland_autostart: []
hyprland_hyprshot_screenshots_retention_days: 14
hyprland_hyprshot_screenshots_dir: ~/pictures/screenshots
hyprland_print_key: PRINT
hyprland_decoration_rounding: 15
hyprland_brightness_level_step: 5

hyprland_hyprsunset_temperature: 5000
hyprland_hyprsunset_time_range: 20:00-09:00

hyprland_hyprlock_font_family: Cantarell
hyprland_hyprlock_monitor: eDP-1
hyprland_hyprlock_time: {size: "230", position: "85"}
hyprland_hyprlock_date: {size: "30", position: "-100"}
hyprland_hyprlock_input: {size: "450, 90", position: "-200"}
hyprland_hyprlock_layout: {size: "18", position: "20"}
