#!/bin/bash

### COMMON ###
alias ll='ls --color=auto -alhF'
alias l='ls --color=auto -lh'
alias diff='diff --color=always'
alias cal='cal -m'
alias rsync='rsync --info=progress2 --no-inc-recursive'
alias dd='dd status=progress'
alias gerp='grep'
alias gti='git'
alias curl-ttfb='curl -sq -o /dev/null -w "Connect: %{time_connect}\nTTFB: %{time_starttransfer}\nTotal time: %{time_total} \n"'
alias crt='cert="cert_`date +%s`"; vim $cert; openssl x509 -in $cert -text -noout | more -11; rm $cert'
alias icat='kitty +kitten icat'
alias ssh='env TERM=xterm ssh'
alias erase="printf '\E[H\E[3J'"
alias tree='tree --dirsfirst'
alias pwgen='pwgen 20'
alias btop='bpytop'
